CREATE TABLE gallery_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guest_uuid  VARCHAR(36)                             NOT NULL,
    image_path  VARCHAR(255)                            NOT NULL,
    audio_path  VARCHAR(255),
    is_approved BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_gallery_items PRIMARY KEY (id)
);