server.port=${PORT:8080}

spring.application.name=${SPRING_APP_NAME:gallery}
spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}

logging.level.com.wedding.gallery=${SPRING_SECURITY_LOG_LEVEL:INFO}
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME}?sslmode=require
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.docker.compose.enabled=false

cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.bucket-name=${R2_BUCKET_NAME}
cloudflare.r2.endpoint=${R2_ENDPOINT}
cloudflare.r2.public-url=${R2_PUBLIC_URL}
front-end.public-url=${FRONTEND_PUBLIC_URL}